issue 11: 마이 페이지 마크업 구현
mentors-service/mentors-service-FE pull request #13
Opened 2022-10-15 08:07 UTC by dlantjdgkgk

1. 마이 페이지 마크업 구현했습니다.
2. 헤더 컴포넌트 구현했습니다.

close #11

2022-10-15 11:45 UTC, jgjgill requested changes

2022-10-15 11:45 UTC, jgjgill commented on src/components/Header/index.tsx
> +export default Header;
https://github.com/mentors-service/mentors-service-FE/blob/a5d8dfcee16ebc4a1572f4c1bcff052b75c79844/src/pages/layout/Layout.tsx#L6
수정하신 헤더에 대한 내용이 layout에는 쓰이고 있지 않는 상태입니다. 확인 부탁드려요

2022-10-15 11:45 UTC, jgjgill commented on src/pages/profile/Profile.tsx
> +          <S.ProfileDescription>
ProfileDescription이라는 이름은 안에 있는 name, description을 담기에는 내용과 상관없는 이름인 것 같아요.

2022-10-15 11:45 UTC, jgjgill commented on src/pages/profile/Profile.tsx
> +    </>
view단이 너무 붙어있어서 흐름을 파악하기가 힘든 것 같아요.
어느 정도 의미가 나뉘는 곳에서는 띄어쓰는게 좋다는 생각이 듭니다.

```suggestion
      <S.ProfileWrapper>
        <S.Profile>
          <img src='/img/ProfileImg.png' alt='' />
          
          <S.ProfileDescription>
            <S.Name>이무성</S.Name>
            <S.Description>저는 5년차 개발자입니다. 주로 react 개발을 위주로 하는 중 입니다.</S.Description>
          </S.ProfileDescription>
        </S.Profile>
        
        <S.MentorSkills>
          <S.Mentor>멘토</S.Mentor>
          <S.Skills>Skills</S.Skills>
        </S.MentorSkills>
      </S.ProfileWrapper>
      
      <S.ProfileBtn>All activity</S.ProfileBtn>
      <S.ProfileBtn>Article</S.ProfileBtn>
      <S.ProfileBtn>Comment</S.ProfileBtn>
    </>
```

2022-10-15 11:45 UTC, jgjgill commented on src/pages/profile/Profile.style.ts
> +`;
Name이라는 이름안에 폰트를 사용하는데 이게 다른 곳에서도 반복해서 쓰더라구요. 근데 다른 곳에서는 Name과는 상관없는 사용처인데 폰트와 관련된 내용은 여기서 지정하지 말고 공통적으로 따로 빼놓고 쓰면 좋을 것 같습니다.

2022-10-15 11:45 UTC, jgjgill commented on src/pages/profile/Profile.style.ts
> +export const ProfileBtn = styled(Name)`
버튼은 button 태그를 사용하는게 좋을 것 같아요

2022-10-15 11:45 UTC, jgjgill commented on src/components/Header/index.tsx
> +    </S.HeaderWrapper>
view단에서는 코드를 조금 나눠도 좋을 것 같아요
```suggestion
    <S.HeaderWrapper>
      <S.LogoName>Mentors</S.LogoName>
      
      <S.BtnWrapper>
        <S.HeaderBtn>
          <img src='/img/ProfileBtn.png' alt='' />
        </S.HeaderBtn>
        
        <S.HeaderBtn>
          <img src='/img/LogoutBtn.png' alt='' />
        </S.HeaderBtn>
      </S.BtnWrapper>
    </S.HeaderWrapper>
```

2022-10-15 11:45 UTC, jgjgill commented on src/components/Header/Header.style.ts
> +`;
공통적으로 사용되는 폰트는 따로 공통 요소로 빼놓는게 좋을 것 같아요

2022-10-15 11:45 UTC, jgjgill commented
style과 관련해서는 지금 저희가 적용한 stylelint를 적용하시지 않는 것 같아요. 린트 적용을 위해 .tsx파일로 변경이 필요해 보입니다. 그리고 피그마에서 스타일 수치 이야기하면 좋을 것 같습니다.

2022-10-16 08:49 UTC, dlantjdgkgk commented on src/pages/profile/Profile.tsx
> +          <S.ProfileDescription>
저도 직관적으로 스타일 이름 정하려다가 그렇게 한 것 같네요. ProfileInfo( 프로필 정보 )로 수정하였습니다.

2022-10-16 08:50 UTC, dlantjdgkgk commented on src/pages/profile/Profile.tsx
> +    </>
네 이 부분은 저도 좋은 것 같네요. 코드를 한 줄이라도 줄이려고 모아놓았네요.

2022-10-16 14:55 UTC, dlantjdgkgk commented on src/pages/profile/Profile.style.ts
> +`;
넵 ThemeProvider이용해서 font 따로 설정해두었습니다. body에 폰트 적용해도 되지만 앞으로 ThemeProvider 쓸 일 있을 것 같아서 미리 세팅해놓았습니다.

2022-10-17 04:52 UTC, merged