Feat/6 react query
mentors-service/mentors-service-FE pull request #7
Opened 2022-10-07 07:46 UTC by dlantjdgkgk

1. 리액트 쿼리를 통한 crud 준비

#6 close

2022-10-07 11:28 UTC, jgjgill commented
CrudAPI.tsx, Setting.tsx은 확장자명을 ts로 변경하고 소문자로 시작하는게 좋을 것 같아요

2022-10-07 12:17 UTC, jgjgill requested changes

2022-10-07 12:17 UTC, jgjgill commented on .env
> +
.gitignore에 추가해야 될 것 같습니다

2022-10-07 12:17 UTC, jgjgill commented on src/api/CrudAPI.tsx
> +  const payload = new FormData();
FormData로 한 이유가 있을까요?
제 생각에는 markdown api를 사용하면서 다 문자열로 처리 가능할 것 같아서요

2022-10-07 12:17 UTC, jgjgill commented on src/index.tsx
> +      <Provider store={store}>
provider가 모여있는게 더 보기 좋을 것 같아요
```suggestion
    <GlobalStyle />
    <QueryClientProvider client={queryClient}>
      <Provider store={store}>
```

2022-10-07 12:17 UTC, jgjgill commented on src/api/CrudAPI.tsx
> +    const res = await apiInstance.put('/', payload, {
put보다는 patch가 더 좋을 것 같아요

2022-10-07 12:17 UTC, jgjgill commented on src/hooks/useGetTodos.tsx
> +}
1. get으로 데이터를 갖고 오는 부분이여서 hook으로 빼놓으신게 맞나요?
2. todos로 파일이름이 되어있어서 article 관련으로 이름을 변경해야 될 것 같아요

2022-10-07 12:17 UTC, jgjgill commented on src/pages/write/Write.tsx
> +    },
react-query에서 onError나 isError 사용하면 crudAPI파일에서 함수마다 try catch로 처리안해도 될 것 같아요

2022-10-08 02:04 UTC, dlantjdgkgk commented on .env
> +
env 파일을 gitignore에 추가하고 구글링을 통해 해결해보려고 했는데 해결이 안돼서 일단 삭제 해 놓은 상태입니다.

2022-10-08 02:05 UTC, dlantjdgkgk commented on src/api/CrudAPI.tsx
> +  const payload = new FormData();
넵 알겠습니다 수정했습니다!

2022-10-08 02:08 UTC, dlantjdgkgk commented on src/index.tsx
> +      <Provider store={store}>
넵 수정했습니다!

2022-10-08 02:11 UTC, dlantjdgkgk commented on src/api/CrudAPI.tsx
> +    const res = await apiInstance.put('/', payload, {
넵 수정했습니다!

2022-10-08 02:13 UTC, dlantjdgkgk commented on src/hooks/useGetTodos.tsx
> +}
넵 맞습니다! 수정하였습니다

2022-10-08 02:13 UTC, dlantjdgkgk commented on src/pages/write/Write.tsx
> +    },
이 부분 좀 더 고민하고 코드 수정해보겠습니다.

2022-10-12 05:11 UTC, jgjgill approved these changes
코드 작성하신거 잘 봤습니다 코멘트한거 확인하시면 무성님이 머지하고 진행해도 괜찮을 것 같아요

2022-10-12 05:11 UTC, jgjgill commented on src/pages/article/Article.tsx
> +  const postkyey = 15;
잠시 테스트로 작성한 코드인 것 같은데 postkyey 오타랑 상수로 사용하는 경우면 이름을 대문자로 구별하면 좋을 것 같아요

2022-10-12 05:11 UTC, jgjgill commented on src/pages/article/Article.tsx
> +        ))}
articles이 있는 경우로 가정할 필요가 있을까요? articles이 없을 때의 기본값을 []로 해도 괜찮지 않을까요?

2022-10-12 06:02 UTC, dlantjdgkgk commented on src/pages/article/Article.tsx
> +  const postkyey = 15;
이름을 대문자로 구별한다는게 파스칼 케이스 이용해서 PostKey 말씀하시는 걸까요? 오타는 수정하였습니다.

2022-10-12 06:04 UTC, dlantjdgkgk commented on src/pages/article/Article.tsx
> +        ))}
articles가 없을 때의 기본값을 []로 한다는 부분이 잘 이해가 안 가네요. 제가 이렇게 코드를 짠 이유는 && 연산자를 통해 articles가 있을 때 데이터를 뿌려주려고 하였습니다.

2022-10-12 06:06 UTC, jgjgill commented on src/pages/article/Article.tsx
> +  const postkyey = 15;
POST_KEY로 생각했습니다

2022-10-12 06:14 UTC, jgjgill commented on src/pages/article/Article.tsx
> +        ))}
view단에서는 최대한 조건같은 로직 없이 최대한 간단해야 하는게 저는 보기 좋다고  생각해요 그래서 article이 있는 경우와 없는 경우로 코드가 안으로 들어가는 구조는 안좋다고 생각해요 article이 없는 경우를 빈 배열로 두고 map으로 돌리면 어차피 빈 배열이여서 아무 데이터도 뿌려주지 않거든요

2022-10-12 06:50 UTC, merged